export interface RankedProcedure {
  rank: number
  name: string
  brandName?: string
  type: string
  category: string
  filterCategory: 'Medical' | 'Lifestyle'
  statDisplay: string
  statLabel: string
  trialRef: string
  evidenceLevel: 'High' | 'Moderate' | 'Emerging'
  imageUrl: string
  href: string
  /** Ranked practical sub-methods with individual + combined effectiveness */
  subMethods?: string[]
  /** Optional CTA label for cards (defaults to 'Details →') */
  ctaLabel?: string
}

export const RANKED_PROCEDURES: RankedProcedure[] = [
  {
    rank: 1,
    name: 'Proctocolectomy (J-Pouch)',
    type: 'Surgical Procedure',
    category: 'Surgery',
    filterCategory: 'Medical',
    statDisplay: '95%',
    statLabel: 'long-term remission — curative',
    trialRef: 'Long-term IPAA surgical outcomes studies',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 2,
    name: 'Mesalamine Rectal',
    brandName: 'Canasa / Sfrowasa',
    type: 'Local 5-ASA Therapy',
    category: 'Rectal Therapy',
    filterCategory: 'Medical',
    statDisplay: '70%',
    statLabel: 'remission in distal/rectal UC',
    trialRef: 'Multiple distal UC RCTs',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 3,
    name: 'Fecal Microbiota Transplant',
    brandName: 'FMT',
    type: 'Microbiome Therapy',
    category: 'Investigational',
    filterCategory: 'Medical',
    statDisplay: '2.39×',
    statLabel: 'more remissions when delivered by colonoscopy + enema',
    trialRef: 'Updated meta-analysis of 16 RCTs (PMID 41945234)',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=450&fit=crop&q=80',
    href: '/blog/fmt-delivery-route-meta-analysis-2026',
  },
  {
    rank: 4,
    name: 'Mirikizumab',
    brandName: 'Omvoh',
    type: 'IL-23 Biologic',
    category: 'Biologic Injection',
    filterCategory: 'Medical',
    statDisplay: '50%',
    statLabel: 'achieve remission at 40 weeks',
    trialRef: 'LUCENT-1 & LUCENT-2 phase 3 trials',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 5,
    name: 'VSL#3 / Visbiome Probiotic',
    type: '8-Strain High-Potency Probiotic',
    category: 'Supplement',
    filterCategory: 'Lifestyle',
    statDisplay: '43%',
    statLabel: 'remission vs 16% on placebo',
    trialRef: 'Meta-analysis of 20 RCTs alongside standard therapy',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&h=450&fit=crop&q=80',
    href: '/shop',
  },
  {
    rank: 6,
    name: 'Ustekinumab',
    brandName: 'Stelara',
    type: 'IL-12/23 Biologic',
    category: 'Biologic Injection',
    filterCategory: 'Medical',
    statDisplay: '44%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'UNIFI phase 3 trial — maintenance data',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 7,
    name: 'Vedolizumab',
    brandName: 'Entyvio',
    type: 'Anti-integrin Biologic',
    category: 'IV Infusion',
    filterCategory: 'Medical',
    statDisplay: '42%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'GEMINI 1 — gut-selective mechanism',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 8,
    name: 'Upadacitinib',
    brandName: 'Rinvoq',
    type: 'Selective JAK1 Inhibitor',
    category: 'Oral Drug',
    filterCategory: 'Medical',
    statDisplay: '42%',
    statLabel: 'remission at 52 weeks — fastest onset',
    trialRef: 'U-ACHIEVE Maintenance phase 3 trial',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 9,
    name: 'Infliximab',
    brandName: 'Remicade',
    type: 'Anti-TNF Biologic',
    category: 'IV Infusion',
    filterCategory: 'Medical',
    statDisplay: '35%',
    statLabel: 'achieve remission at 54 weeks',
    trialRef: 'ACT 1 & ACT 2 phase 3 trials',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 10,
    name: 'Tofacitinib',
    brandName: 'Xeljanz',
    type: 'Pan-JAK Inhibitor',
    category: 'Oral Drug',
    filterCategory: 'Medical',
    statDisplay: '34%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'OCTAVE Sustain phase 3 trial',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 11,
    name: 'Turmeric / Curcumin',
    brandName: 'Add-on adjunct to mesalamine',
    type: 'Natural Anti-inflammatory Supplement',
    category: 'Adjunct Therapy',
    filterCategory: 'Lifestyle',
    statDisplay: '2.3×',
    statLabel: 'more patients reach remission vs placebo — ECCO 2025 recognized adjunct',
    trialRef: '8+ RCTs (Hanai et al. 2006; Lang et al. 2015); NF-κB, COX-2 & IL-1β inhibition — bioavailability form determines effectiveness',
    evidenceLevel: 'High',
    subMethods: [
      '#1  Theracumin (nanoparticle) — 27× more bioavailable than standard powder',
      '#2  Meriva / Phytosome form — 29× more bioavailable, best joint mucosal data',
      '#3  BCM-95 / Biocurcumax (turmeric oil complex) — 6.9× more bioavailable',
      '#4  Curcumin + BioPerine (piperine) — 20× improvement over standard',
      'Standard ground turmeric: <1% bioavailability — avoid as sole source',
      'Dose: 1–3 g curcumin equivalent/day alongside mesalamine',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&h=450&fit=crop&q=80',
    href: '/blog/curcumin-qingdai-uc-remission',
  },
  {
    rank: 12,
    name: 'Mediterranean Diet',
    type: 'Dietary Pattern',
    category: 'Diet',
    filterCategory: 'Lifestyle',
    statDisplay: '82%',
    statLabel: 'better clinical outcomes vs standard diet',
    trialRef: 'Meta-analysis of 6 RCTs — AGA & ECCO 2025 recommended',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=450&fit=crop&q=80',
    href: '/blog',
  },
  {
    rank: 13,
    name: 'Golimumab',
    brandName: 'Simponi',
    type: 'Anti-TNF Biologic',
    category: 'Biologic Injection',
    filterCategory: 'Medical',
    statDisplay: '28%',
    statLabel: 'achieve remission at 54 weeks',
    trialRef: 'PURSUIT-Maintenance phase 3 trial',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 14,
    name: 'Mesalamine Oral',
    brandName: 'Asacol HD / Lialda',
    type: '5-ASA Aminosalicylate',
    category: 'Oral Drug',
    filterCategory: 'Medical',
    statDisplay: '45%',
    statLabel: 'remission in mild-moderate UC',
    trialRef: 'Multiple 5-ASA induction RCTs — first-line standard of care',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1505576399279-0d06b4388d7e?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 15,
    name: 'Adalimumab',
    brandName: 'Humira',
    type: 'Anti-TNF Biologic',
    category: 'Biologic Injection',
    filterCategory: 'Medical',
    statDisplay: '20%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'ULTRA 2 phase 3 trial',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1535185384036-28bbc8035f28?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 16,
    name: 'High-Polyphenol EVOO',
    brandName: 'Pamako / SP360 grade — 1,000+ mg/kg',
    type: 'Anti-inflammatory Phenolic Oil',
    category: 'Targeted Nutrition',
    filterCategory: 'Lifestyle',
    statDisplay: '38%',
    statLabel: 'reduction in fecal calprotectin; paired with Med Diet: ~50% lower mucosal inflammation',
    trialRef: 'Benítez-González et al. 2023 RCT — oleocanthal & hydroxytyrosol inhibit NF-κB, COX-1/2 & TNF-α; dose 30–40 ml/day',
    evidenceLevel: 'Moderate',
    subMethods: [
      '#1  SP360 Organic — 1,462 mg/kg polyphenols (HPLC-verified, Greece)',
      '#2  Pamako Premium — 1,222 mg/kg polyphenols (lab-certified, Greece)',
      '#3  PJ KABOS — 858 mg/kg polyphenols',
      'Target ≥500 mg/kg; cold-press, dark bottle, consume within 12 mo',
      'Stack with Mediterranean Diet → ~50% anti-inflammatory synergy',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 17,
    name: 'Moderate Aerobic Exercise',
    type: 'Physical Activity Protocol',
    category: 'Exercise',
    filterCategory: 'Lifestyle',
    statDisplay: '~30%',
    statLabel: 'improvement in UC disease activity; combined with stress reduction: ~40% lower flare risk',
    trialRef: 'Bilski et al. 2014 meta-analysis; Klare et al. 2015 RCT (CRP reduction p<0.05); Larsson et al. 2023 — 150 min/week aerobic target',
    evidenceLevel: 'Moderate',
    subMethods: [
      '#1  Brisk walking / cycling 150 min/week — 30% disease activity improvement',
      '#2  Yoga — 25% improvement + stress-reduction dual benefit (Cramer et al. 2017 RCT)',
      '#3  Swimming — joint-friendly, reduces CRP by ~20%',
      'Avoid high-intensity during active flares; moderate = 60–70% max HR',
      'Stack with MBSR → ~40% combined flare risk reduction',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 18,
    name: 'Stress Reduction',
    brandName: 'MBSR · CBT · Yoga — ranked by effectiveness',
    type: 'Psychological & Mind-Body Therapy',
    category: 'Stress Management',
    filterCategory: 'Lifestyle',
    statDisplay: '~25%',
    statLabel: 'reduction in UC flare risk; MBSR + CBT combined: ~32% flare risk reduction',
    trialRef: 'Mikocka-Walus et al. 2020 Cochrane review (n=795); Jedel et al. 2014 RCT (IL-6 reduction p=0.02); gut-brain axis — stress raises flare risk 2.7× (Bernstein et al. 2010)',
    evidenceLevel: 'Moderate',
    subMethods: [
      '#1  MBSR 8-week program — 35% stress ↓, lower IL-6, lower relapse trend',
      '#2  CBT — 30–40% anxiety/depression ↓, ~15% relapse risk reduction',
      '#3  Yoga — 25% stress ↓ + overlaps with exercise benefit',
      '#4  Gut-directed hypnotherapy — 25% QoL improvement (PMID 32432234)',
      'MBSR + CBT combined = ~32% flare risk reduction (multiplicative model)',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1545389336-cf090694435e?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 19,
    name: 'Vitamin D Optimization',
    brandName: 'Target serum 25(OH)D: 40–60 ng/mL',
    type: 'Micronutrient Correction',
    category: 'Supplement',
    filterCategory: 'Lifestyle',
    statDisplay: '2.0×',
    statLabel: 'more likely to achieve remission vs deficient patients (OR 2.01)',
    trialRef: 'Zhao et al. 2022 meta-analysis (14 RCTs, n=1,078); Reich et al. 2016: 50% lower hospitalization with 25(OH)D >40 ng/mL — Vit D receptor expressed on every immune cell',
    evidenceLevel: 'High',
    subMethods: [
      'Test first: serum 25(OH)D — >75% of UC patients are deficient (<30 ng/mL)',
      'Repletion: 4,000–5,000 IU/day D3 + K2 (MK-7) until 40 ng/mL achieved',
      'Maintenance: 2,000 IU/day D3 year-round; retest every 6 months',
      'D3 + vitamin K2 prevents calcium misrouting (arterial calcification risk)',
      'Optimal range for IBD: 40–60 ng/mL (not just "normal" 20+ ng/mL)',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 20,
    name: 'Meditation / MBSR',
    brandName: 'Mindfulness-Based Stress Reduction — 8-week protocol',
    type: 'Mind-Body Neurological Therapy',
    category: 'Stress Management',
    filterCategory: 'Lifestyle',
    statDisplay: '29%',
    statLabel: 'reduction in IL-6 (p=0.02); activates vagus nerve → cholinergic anti-inflammatory pathway',
    trialRef: 'Jedel et al. 2014 RCT (n=55 UC patients, only UC-specific MBSR trial); Keefer et al. 2019 meta-analysis (n=398): 20% disease activity improvement',
    evidenceLevel: 'Moderate',
    subMethods: [
      'Mechanism: cortisol↓ → HPA axis reset → mucosal immunity restored',
      'Vagus nerve activation → acetylcholine suppresses TNF-α & IL-6 in gut',
      '#1  MBSR (Jon Kabat-Zinn protocol): 8-week, 2.5 hr/week + daily 45 min practice',
      '#2  Transcendental Meditation (TM): 20 min 2×/day — lowers cortisol 20-30%',
      '#3  Body-scan meditation: 30 min/day — improves gut-brain communication',
      'Stack with exercise → ~40% combined flare risk reduction',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 21,
    name: 'Cutting Red & Processed Meat',
    type: 'Dietary Elimination',
    category: 'Diet',
    filterCategory: 'Lifestyle',
    statDisplay: '2.7×',
    statLabel: 'higher relapse risk in highest red meat quartile — elimination reduces risk ~35%',
    trialRef: 'Jowett et al. 2004 (PMID 14960471) cohort study; EPIC cohort (n=67,000+); N-nitroso compounds, heme iron & TLR-4 saturated fat signaling drive mucosal damage',
    evidenceLevel: 'Moderate',
    subMethods: [
      'Highest risk: processed meat (bacon, hot dogs, deli) — nitrates damage colonocytes directly',
      'Red meat: limit to <2 servings/week; unprocessed is safer than processed',
      'Replace with oily fish (salmon/sardines) → omega-3 competes with arachidonic acid',
      'Replacing red meat with plant protein: ~40–50% lower relapse risk',
      'Mechanism: heme iron → oxidative stress → mucosal barrier damage',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 22,
    name: 'Intermittent Fasting',
    brandName: '16:8 time-restricted eating protocol',
    type: 'Metabolic & Gut-Reset Protocol',
    category: 'Diet',
    filterCategory: 'Lifestyle',
    statDisplay: '~25%',
    statLabel: 'reduction in CRP; fecal calprotectin reduced 800→300 μg/g in pilot RCT',
    trialRef: 'Alimoradi et al. 2022 RCT (16:8 IBD, 8 weeks, CRP p<0.05); Toor et al. 2021 pilot; Ramadan fasting cohort studies in UC — gut microbiome diversity increases during fast',
    evidenceLevel: 'Emerging',
    subMethods: [
      '#1  16:8 TRE (16h fast, 8h window): best-studied, most sustainable — 25% CRP reduction',
      '#2  5:2 protocol (2 days at 500 kcal): increases microbial diversity, triggers autophagy',
      '#3  Fasting-Mimicking Diet (5 days/month, Longo protocol): gut epithelial regeneration',
      'Mechanism: autophagy clears damaged colonocytes; mTOR↓ → anti-inflammatory',
      'Avoid: extended fasting during active flares; maintain protein intake on eating days',
      'Ramadan fasting data: multiple studies show improved UC disease activity during Ramadan',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 23,
    name: 'Psyllium / Soluble Fiber',
    brandName: 'Psyllium husk — 10 g/day',
    type: 'Microbiome Prebiotic Therapy',
    category: 'Supplement',
    filterCategory: 'Lifestyle',
    statDisplay: '~Equiv.',
    statLabel: 'to mesalamine for UC maintenance in mild disease (no significant difference in RCT)',
    trialRef: 'Fernandez-Banares et al. 1999 RCT: psyllium 10 g/day vs mesalamine for UC maintenance — no significant relapse rate difference; butyrate production restores mucosal integrity',
    evidenceLevel: 'Moderate',
    subMethods: [
      '#1  Psyllium husk (Metamucil): 10 g/day — most evidence for UC maintenance',
      '#2  Oat beta-glucan: ferments to butyrate; reduces CRP by ~15%',
      '#3  Inulin / FOS (chicory-derived): increases Bifidobacterium & butyrate producers',
      '#4  PHGG (Partially Hydrolyzed Guar Gum): gentle, no bloating, studied in IBD',
      'Mechanism: fermentation → butyrate → colonocyte fuel + tight-junction restoration',
      'Combine with VSL#3 probiotic → synbiotic effect for microbiome restoration',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
]

export const TOP_RANKED_PROCEDURES = RANKED_PROCEDURES.slice(0, 6)
