export interface RankedProcedure {
  rank: number
  name: string
  brandName?: string
  type: string
  category: string
  statDisplay: string
  statLabel: string
  trialRef: string
  evidenceLevel: 'High' | 'Moderate' | 'Emerging'
  gradientClass: string
  href: string
}

// Ranked by estimated % of patients achieving remission based on clinical trial data
export const RANKED_PROCEDURES: RankedProcedure[] = [
  {
    rank: 1,
    name: 'Proctocolectomy (J-Pouch)',
    type: 'Surgical Procedure',
    category: 'Surgery',
    statDisplay: '95%',
    statLabel: 'achieve long-term remission (curative)',
    trialRef: 'Long-term IPAA surgical outcomes studies — for refractory or severe UC',
    evidenceLevel: 'High',
    gradientClass: 'from-orange-900 via-amber-900/70 to-yellow-950',
    href: '/rankings',
  },
  {
    rank: 2,
    name: 'Mesalamine Rectal',
    brandName: 'Canasa / Sfrowasa',
    type: 'Local 5-ASA Therapy',
    category: 'Rectal Therapy',
    statDisplay: '70%',
    statLabel: 'achieve remission in distal/rectal UC',
    trialRef: 'Multiple distal UC RCTs — for disease limited to left colon or rectum',
    evidenceLevel: 'High',
    gradientClass: 'from-rose-900 via-pink-900/70 to-red-950',
    href: '/rankings',
  },
  {
    rank: 3,
    name: 'Fecal Microbiota Transplant',
    brandName: 'FMT',
    type: 'Microbiome Therapy',
    category: 'Investigational',
    statDisplay: '62%',
    statLabel: 'achieve remission in meta-analysis',
    trialRef: 'Meta-analysis of 15 RCTs, OR 2.65 (PMID 41078065)',
    evidenceLevel: 'High',
    gradientClass: 'from-blue-900 via-indigo-900/70 to-violet-950',
    href: '/blog/fmt-uc-remission',
  },
  {
    rank: 4,
    name: 'Mirikizumab',
    brandName: 'Omvoh',
    type: 'IL-23 Biologic',
    category: 'Biologic Injection',
    statDisplay: '50%',
    statLabel: 'achieve remission at 40 weeks',
    trialRef: 'LUCENT-1 & LUCENT-2 phase 3 trials',
    evidenceLevel: 'High',
    gradientClass: 'from-teal-900 via-cyan-900/70 to-blue-950',
    href: '/rankings',
  },
  {
    rank: 5,
    name: 'VSL#3 / Visbiome Probiotic',
    type: '8-Strain High-Potency Probiotic',
    category: 'Supplement',
    statDisplay: '43%',
    statLabel: 'achieve remission vs 16% on placebo',
    trialRef: 'Meta-analysis of 20 RCTs — used alongside standard therapy',
    evidenceLevel: 'High',
    gradientClass: 'from-indigo-900 via-blue-900/70 to-sky-950',
    href: '/shop',
  },
  {
    rank: 6,
    name: 'Ustekinumab',
    brandName: 'Stelara',
    type: 'IL-12/23 Biologic',
    category: 'Biologic Injection',
    statDisplay: '44%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'UNIFI phase 3 trial — maintenance data',
    evidenceLevel: 'High',
    gradientClass: 'from-violet-900 via-purple-900/70 to-fuchsia-950',
    href: '/rankings',
  },
  {
    rank: 7,
    name: 'Vedolizumab',
    brandName: 'Entyvio',
    type: 'Anti-integrin Biologic',
    category: 'IV Infusion',
    statDisplay: '42%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'GEMINI 1 phase 3 trial — gut-selective mechanism',
    evidenceLevel: 'High',
    gradientClass: 'from-green-900 via-emerald-900/70 to-teal-950',
    href: '/rankings',
  },
  {
    rank: 8,
    name: 'Upadacitinib',
    brandName: 'Rinvoq',
    type: 'JAK1 Inhibitor',
    category: 'Oral Drug',
    statDisplay: '42%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'U-ACHIEVE Maintenance — fastest induction of all oral agents',
    evidenceLevel: 'High',
    gradientClass: 'from-emerald-900 via-teal-900/70 to-emerald-950',
    href: '/rankings',
  },
  {
    rank: 9,
    name: 'Infliximab',
    brandName: 'Remicade',
    type: 'Anti-TNF Biologic',
    category: 'IV Infusion',
    statDisplay: '35%',
    statLabel: 'achieve remission at 54 weeks',
    trialRef: 'ACT 1 & ACT 2 phase 3 trials',
    evidenceLevel: 'High',
    gradientClass: 'from-cyan-900 via-sky-900/70 to-blue-950',
    href: '/rankings',
  },
  {
    rank: 10,
    name: 'Tofacitinib',
    brandName: 'Xeljanz',
    type: 'Pan-JAK Inhibitor',
    category: 'Oral Drug',
    statDisplay: '34%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'OCTAVE Sustain phase 3 trial',
    evidenceLevel: 'High',
    gradientClass: 'from-amber-900 via-orange-900/70 to-yellow-950',
    href: '/rankings',
  },
  {
    rank: 11,
    name: 'Curcumin (Add-on)',
    type: 'Natural Supplement',
    category: 'Adjunct Therapy',
    statDisplay: '2.3x',
    statLabel: 'more patients reach remission vs placebo',
    trialRef: '8+ RCTs — ECCO 2025 recognized adjunct to mesalamine',
    evidenceLevel: 'High',
    gradientClass: 'from-yellow-900 via-amber-900/70 to-orange-950',
    href: '/blog/curcumin-qingdai-uc-remission',
  },
  {
    rank: 12,
    name: 'Mediterranean Diet',
    type: 'Dietary Pattern',
    category: 'Diet',
    statDisplay: '82%',
    statLabel: 'better clinical outcomes vs standard diet',
    trialRef: 'Meta-analysis of 6 RCTs — AGA & ECCO 2025 recommended',
    evidenceLevel: 'High',
    gradientClass: 'from-lime-900 via-green-900/70 to-emerald-950',
    href: '/blog',
  },
  {
    rank: 13,
    name: 'Golimumab',
    brandName: 'Simponi',
    type: 'Anti-TNF Biologic',
    category: 'Biologic Injection',
    statDisplay: '28%',
    statLabel: 'achieve remission at 54 weeks',
    trialRef: 'PURSUIT-Maintenance phase 3 trial',
    evidenceLevel: 'High',
    gradientClass: 'from-sky-900 via-blue-900/70 to-indigo-950',
    href: '/rankings',
  },
  {
    rank: 14,
    name: 'Mesalamine Oral',
    brandName: 'Asacol HD / Lialda',
    type: '5-ASA Aminosalicylate',
    category: 'Oral Drug',
    statDisplay: '45%',
    statLabel: 'achieve remission in mild-moderate UC',
    trialRef: 'Multiple 5-ASA induction RCTs — first-line standard of care',
    evidenceLevel: 'High',
    gradientClass: 'from-teal-900 via-emerald-900/70 to-green-950',
    href: '/rankings',
  },
  {
    rank: 15,
    name: 'Adalimumab',
    brandName: 'Humira',
    type: 'Anti-TNF Biologic',
    category: 'Biologic Injection',
    statDisplay: '20%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'ULTRA 2 phase 3 trial',
    evidenceLevel: 'High',
    gradientClass: 'from-slate-800 via-gray-800/70 to-slate-950',
    href: '/rankings',
  },
]

export const TOP_RANKED_PROCEDURES = RANKED_PROCEDURES.slice(0, 6)
