export interface RankedProcedure {
  rank: number
  name: string
  brandName?: string
  type: string
  category: string
  filterCategory: 'Medical' | 'Lifestyle'
  statDisplay: string
  statLabel: string
  trialRef: string
  evidenceLevel: 'High' | 'Moderate' | 'Emerging'
  imageUrl: string
  href: string
}

export const RANKED_PROCEDURES: RankedProcedure[] = [
  {
    rank: 1,
    name: 'Proctocolectomy (J-Pouch)',
    type: 'Surgical Procedure',
    category: 'Surgery',
    filterCategory: 'Medical',
    statDisplay: '95%',
    statLabel: 'long-term remission — curative',
    trialRef: 'Long-term IPAA surgical outcomes studies',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 2,
    name: 'Mesalamine Rectal',
    brandName: 'Canasa / Sfrowasa',
    type: 'Local 5-ASA Therapy',
    category: 'Rectal Therapy',
    filterCategory: 'Medical',
    statDisplay: '70%',
    statLabel: 'remission in distal/rectal UC',
    trialRef: 'Multiple distal UC RCTs',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 3,
    name: 'Fecal Microbiota Transplant',
    brandName: 'FMT',
    type: 'Microbiome Therapy',
    category: 'Investigational',
    filterCategory: 'Medical',
    statDisplay: '62%',
    statLabel: 'achieve remission in meta-analysis',
    trialRef: 'Meta-analysis of 15 RCTs (PMID 41078065)',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&h=450&fit=crop&q=80',
    href: '/blog/fmt-uc-remission',
  },
  {
    rank: 4,
    name: 'Mirikizumab',
    brandName: 'Omvoh',
    type: 'IL-23 Biologic',
    category: 'Biologic Injection',
    filterCategory: 'Medical',
    statDisplay: '50%',
    statLabel: 'achieve remission at 40 weeks',
    trialRef: 'LUCENT-1 & LUCENT-2 phase 3 trials',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 5,
    name: 'VSL#3 / Visbiome Probiotic',
    type: '8-Strain High-Potency Probiotic',
    category: 'Supplement',
    filterCategory: 'Lifestyle',
    statDisplay: '43%',
    statLabel: 'remission vs 16% on placebo',
    trialRef: 'Meta-analysis of 20 RCTs alongside standard therapy',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&h=450&fit=crop&q=80',
    href: '/shop',
  },
  {
    rank: 6,
    name: 'Ustekinumab',
    brandName: 'Stelara',
    type: 'IL-12/23 Biologic',
    category: 'Biologic Injection',
    filterCategory: 'Medical',
    statDisplay: '44%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'UNIFI phase 3 trial — maintenance data',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 7,
    name: 'Vedolizumab',
    brandName: 'Entyvio',
    type: 'Anti-integrin Biologic',
    category: 'IV Infusion',
    filterCategory: 'Medical',
    statDisplay: '42%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'GEMINI 1 — gut-selective mechanism',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 8,
    name: 'Upadacitinib',
    brandName: 'Rinvoq',
    type: 'Selective JAK1 Inhibitor',
    category: 'Oral Drug',
    filterCategory: 'Medical',
    statDisplay: '42%',
    statLabel: 'remission at 52 weeks — fastest onset',
    trialRef: 'U-ACHIEVE Maintenance phase 3 trial',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 9,
    name: 'Infliximab',
    brandName: 'Remicade',
    type: 'Anti-TNF Biologic',
    category: 'IV Infusion',
    filterCategory: 'Medical',
    statDisplay: '35%',
    statLabel: 'achieve remission at 54 weeks',
    trialRef: 'ACT 1 & ACT 2 phase 3 trials',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 10,
    name: 'Tofacitinib',
    brandName: 'Xeljanz',
    type: 'Pan-JAK Inhibitor',
    category: 'Oral Drug',
    filterCategory: 'Medical',
    statDisplay: '34%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'OCTAVE Sustain phase 3 trial',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 11,
    name: 'Curcumin (Add-on)',
    type: 'Natural Supplement',
    category: 'Adjunct Therapy',
    filterCategory: 'Lifestyle',
    statDisplay: '2.3×',
    statLabel: 'more patients reach remission vs placebo',
    trialRef: '8+ RCTs — ECCO 2025 recognized adjunct to mesalamine',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&h=450&fit=crop&q=80',
    href: '/blog/curcumin-qingdai-uc-remission',
  },
  {
    rank: 12,
    name: 'Mediterranean Diet',
    type: 'Dietary Pattern',
    category: 'Diet',
    filterCategory: 'Lifestyle',
    statDisplay: '82%',
    statLabel: 'better clinical outcomes vs standard diet',
    trialRef: 'Meta-analysis of 6 RCTs — AGA & ECCO 2025 recommended',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=450&fit=crop&q=80',
    href: '/blog',
  },
  {
    rank: 13,
    name: 'Golimumab',
    brandName: 'Simponi',
    type: 'Anti-TNF Biologic',
    category: 'Biologic Injection',
    filterCategory: 'Medical',
    statDisplay: '28%',
    statLabel: 'achieve remission at 54 weeks',
    trialRef: 'PURSUIT-Maintenance phase 3 trial',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 14,
    name: 'Mesalamine Oral',
    brandName: 'Asacol HD / Lialda',
    type: '5-ASA Aminosalicylate',
    category: 'Oral Drug',
    filterCategory: 'Medical',
    statDisplay: '45%',
    statLabel: 'remission in mild-moderate UC',
    trialRef: 'Multiple 5-ASA induction RCTs — first-line standard of care',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1505576399279-0d06b4388d7e?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
  {
    rank: 15,
    name: 'Adalimumab',
    brandName: 'Humira',
    type: 'Anti-TNF Biologic',
    category: 'Biologic Injection',
    filterCategory: 'Medical',
    statDisplay: '20%',
    statLabel: 'achieve remission at 52 weeks',
    trialRef: 'ULTRA 2 phase 3 trial',
    evidenceLevel: 'High',
    imageUrl: 'https://images.unsplash.com/photo-1535185384036-28bbc8035f28?w=800&h=450&fit=crop&q=80',
    href: '/rankings',
  },
]

export const TOP_RANKED_PROCEDURES = RANKED_PROCEDURES.slice(0, 6)
