export type Treatment = {
  id: number
  rank: number
  name: string
  brandNames?: string
  className: string
  route: string
  severity: string
  trials: string
  responseRate: string
  remissionRate: string
  keySideEffects: string
  yearApproved: string
  notes: string
}

export const TREATMENTS: Treatment[] = [
  {
    id: 1,
    rank: 1,
    name: 'Mesalamine',
    brandNames: 'Asacol HD, Lialda, Pentasa',
    className: '5-ASA / Aminosalicylate',
    route: 'Oral, often paired with rectal therapy',
    severity: 'First-line for mild to moderate UC',
    trials: 'Multiple mesalamine induction and maintenance RCTs',
    responseRate: 'Not standardized across older formulation trials',
    remissionRate: '~40-50% in mild-moderate UC',
    keySideEffects: 'Headache, nausea, abdominal discomfort, rare nephrotoxicity',
    yearApproved: '1987 (formulation-specific)',
    notes: 'Gold-standard first-line option for mild-moderate disease; often escalated with rectal mesalamine for left-sided or distal inflammation.',
  },
  {
    id: 2,
    rank: 2,
    name: 'Sulfasalazine',
    className: '5-ASA / Aminosalicylate',
    route: 'Oral',
    severity: 'Mild to moderate UC',
    trials: 'Older sulfasalazine induction and maintenance trials',
    responseRate: 'Older endpoints vary across studies',
    remissionRate: '~40%',
    keySideEffects: 'Nausea, headache, rash, reversible male infertility, sulfa intolerance',
    yearApproved: '1950',
    notes: 'The oldest 5-ASA option. More side effects than mesalamine, but often the lowest-cost oral therapy.',
  },
  {
    id: 3,
    rank: 3,
    name: 'Balsalazide',
    brandNames: 'Colazal',
    className: '5-ASA / Aminosalicylate',
    route: 'Oral',
    severity: 'Mild to moderate UC',
    trials: 'Comparator trials versus mesalamine-based therapy',
    responseRate: 'Clinical improvement seen, but trial endpoints vary',
    remissionRate: '~45%',
    keySideEffects: 'Headache, abdominal pain, nausea, diarrhea',
    yearApproved: '2000',
    notes: 'A well-tolerated prodrug that delivers mesalamine to the colon.',
  },
  {
    id: 4,
    rank: 4,
    name: 'Olsalazine',
    brandNames: 'Dipentum',
    className: '5-ASA / Aminosalicylate',
    route: 'Oral',
    severity: 'Mild to moderate UC',
    trials: 'Older induction and maintenance mesalamine comparator studies',
    responseRate: 'Not directly standardized',
    remissionRate: 'Similar efficacy to other 5-ASA options',
    keySideEffects: 'Diarrhea, cramping, headache',
    yearApproved: '1990',
    notes: 'Less commonly used today, largely because diarrhea can limit tolerability.',
  },
  {
    id: 5,
    rank: 5,
    name: 'Infliximab',
    brandNames: 'Remicade',
    className: 'Biologic, anti-TNF',
    route: 'IV infusion',
    severity: 'Moderate to severe UC',
    trials: 'ACT 1 and ACT 2',
    responseRate: '~45-65% clinical response',
    remissionRate: '~30-35% at week 8',
    keySideEffects: 'Infusion reactions, serious infections, TB/hepatitis B reactivation',
    yearApproved: '2005 (UC)',
    notes: 'A foundational anti-TNF with strong induction data and major real-world experience in steroid-refractory disease.',
  },
  {
    id: 6,
    rank: 6,
    name: 'Adalimumab',
    brandNames: 'Humira',
    className: 'Biologic, anti-TNF',
    route: 'Subcutaneous injection',
    severity: 'Moderate to severe UC',
    trials: 'ULTRA 1 and ULTRA 2',
    responseRate: '~50%',
    remissionRate: '~17-19% at week 8',
    keySideEffects: 'Injection-site reactions, infections, TB/hepatitis B reactivation',
    yearApproved: '2012 (UC)',
    notes: 'A self-injected anti-TNF used when home dosing is preferred over infusion-center therapy.',
  },
  {
    id: 7,
    rank: 7,
    name: 'Golimumab',
    brandNames: 'Simponi',
    className: 'Biologic, anti-TNF',
    route: 'Subcutaneous injection',
    severity: 'Moderate to severe UC',
    trials: 'PURSUIT-SC and PURSUIT-Maintenance',
    responseRate: '~51%',
    remissionRate: '~18% at week 6',
    keySideEffects: 'Injection-site reactions, infections, TB/hepatitis B reactivation',
    yearApproved: '2013 (UC)',
    notes: 'Another anti-TNF option, often considered when a monthly injection schedule is attractive.',
  },
  {
    id: 8,
    rank: 8,
    name: 'Vedolizumab',
    brandNames: 'Entyvio',
    className: 'Biologic, anti-integrin (gut selective)',
    route: 'IV infusion or subcutaneous maintenance',
    severity: 'Moderate to severe UC',
    trials: 'GEMINI 1',
    responseRate: '~47%',
    remissionRate: '~17% at week 6, ~42% at week 52',
    keySideEffects: 'Headache, nasopharyngitis, arthralgia, infusion reactions',
    yearApproved: '2014 (UC)',
    notes: 'Excellent safety profile and gut-selective mechanism make it a common choice when systemic immunosuppression is a concern.',
  },
  {
    id: 9,
    rank: 9,
    name: 'Ustekinumab',
    brandNames: 'Stelara',
    className: 'Biologic, anti-IL-12/23',
    route: 'IV induction, subcutaneous maintenance',
    severity: 'Moderate to severe UC',
    trials: 'UNIFI',
    responseRate: '~62%',
    remissionRate: '~16% at week 8',
    keySideEffects: 'Infections, headache, injection-site reactions',
    yearApproved: '2019 (UC)',
    notes: 'Useful for patients needing a non-anti-TNF mechanism with a relatively favorable safety reputation.',
  },
  {
    id: 10,
    rank: 10,
    name: 'Mirikizumab',
    brandNames: 'Omvoh',
    className: 'Biologic, anti-IL-23p19',
    route: 'IV induction, subcutaneous maintenance',
    severity: 'Moderate to severe UC',
    trials: 'LUCENT-1 and LUCENT-2',
    responseRate: '~63%',
    remissionRate: '~24% at week 12',
    keySideEffects: 'Infections, arthralgia, elevated liver enzymes, headache',
    yearApproved: '2023 (UC)',
    notes: 'A newer IL-23 therapy with strong induction data and a modern cytokine-targeted mechanism.',
  },
  {
    id: 11,
    rank: 11,
    name: 'Risankizumab',
    brandNames: 'Skyrizi',
    className: 'Biologic, anti-IL-23p19',
    route: 'IV induction, subcutaneous maintenance',
    severity: 'Moderate to severe UC',
    trials: 'INSPIRE and COMMAND',
    responseRate: 'Advanced-therapy response benefit shown in phase 3 trials',
    remissionRate: '~20% at week 12',
    keySideEffects: 'Upper respiratory infections, headache, injection reactions',
    yearApproved: '2024 (UC)',
    notes: 'Approved for UC in 2024, expanding the IL-23 class for patients who want another advanced-therapy option.',
  },
  {
    id: 12,
    rank: 12,
    name: 'Tofacitinib',
    brandNames: 'Xeljanz',
    className: 'Small molecule, pan-JAK inhibitor',
    route: 'Oral',
    severity: 'Moderate to severe UC',
    trials: 'OCTAVE Induction and OCTAVE Sustain',
    responseRate: '~59%',
    remissionRate: '~19% at week 8',
    keySideEffects: 'Herpes zoster, lipid changes, serious infection, thrombosis warning',
    yearApproved: '2018 (UC)',
    notes: 'Rapid-onset oral therapy, but systemic safety warnings mean patient selection and monitoring matter.',
  },
  {
    id: 13,
    rank: 13,
    name: 'Upadacitinib',
    brandNames: 'Rinvoq',
    className: 'Small molecule, selective JAK1 inhibitor',
    route: 'Oral',
    severity: 'Moderate to severe UC',
    trials: 'U-ACHIEVE and U-ACCOMPLISH',
    responseRate: '~74%',
    remissionRate: '~26% at week 8',
    keySideEffects: 'Herpes zoster, acne, lipid elevation, thrombosis warning, serious infection',
    yearApproved: '2022 (UC)',
    notes: 'One of the fastest and most effective oral induction options in the brief, especially when speed matters.',
  },
  {
    id: 14,
    rank: 14,
    name: 'Ozanimod',
    brandNames: 'Zeposia',
    className: 'Small molecule, S1P receptor modulator',
    route: 'Oral',
    severity: 'Moderate to severe UC',
    trials: 'TRUE NORTH',
    responseRate: '~48%',
    remissionRate: '~18% at week 10',
    keySideEffects: 'Bradycardia, liver enzyme elevation, macular edema, infection risk',
    yearApproved: '2021 (UC)',
    notes: 'An oral non-JAK advanced therapy that requires baseline cardiac and ophthalmic awareness in selected patients.',
  },
  {
    id: 15,
    rank: 15,
    name: 'Etrasimod',
    brandNames: 'Velsipity',
    className: 'Small molecule, S1P receptor modulator',
    route: 'Oral',
    severity: 'Moderate to severe UC',
    trials: 'ELEVATE UC 12 and ELEVATE UC 52',
    responseRate: '~53% at week 12',
    remissionRate: 'Maintenance remission benefit shown through week 52',
    keySideEffects: 'Bradycardia, headache, elevated liver enzymes, infection risk',
    yearApproved: '2023 (UC)',
    notes: 'Approved in 2023 and positioned as another oral alternative to biologics or JAK inhibitors.',
  },
  {
    id: 16,
    rank: 16,
    name: 'Prednisone',
    className: 'Corticosteroid',
    route: 'Oral',
    severity: 'Short-term induction only',
    trials: 'Historical corticosteroid induction studies',
    responseRate: '~60-70%',
    remissionRate: 'Not for maintenance',
    keySideEffects: 'Bone loss, hyperglycemia, mood change, insomnia, infection risk',
    yearApproved: '1955',
    notes: 'Very effective at short-term flare control, but prolonged use drives major toxicity and dependency problems.',
  },
  {
    id: 17,
    rank: 17,
    name: 'Budesonide MMX',
    brandNames: 'Uceris',
    className: 'Corticosteroid',
    route: 'Oral',
    severity: 'Mild to moderate induction, especially when 5-ASA is inadequate',
    trials: 'CORE I and CORE II',
    responseRate: 'Symptom improvement without the same systemic steroid burden',
    remissionRate: '~18% at week 8',
    keySideEffects: 'Headache, nausea, edema, milder steroid effects',
    yearApproved: '2013',
    notes: 'A colon-targeted steroid with fewer systemic effects than prednisone, but still not a maintenance drug.',
  },
  {
    id: 18,
    rank: 18,
    name: 'Azathioprine / 6-MP',
    className: 'Immunomodulator',
    route: 'Oral',
    severity: 'Steroid-sparing maintenance adjunct',
    trials: 'Thiopurine maintenance studies',
    responseRate: 'Used more for steroid-sparing maintenance than rapid induction',
    remissionRate: '~40-60% maintain remission as adjunct',
    keySideEffects: 'Leukopenia, hepatotoxicity, pancreatitis, infection risk',
    yearApproved: '1968',
    notes: 'Slow onset of 3-6 months limits flare utility, but thiopurines still appear in combination strategies.',
  },
  {
    id: 19,
    rank: 19,
    name: 'Methotrexate',
    className: 'Immunomodulator',
    route: 'Oral or subcutaneous',
    severity: 'Occasionally used off-label or when other options are limited',
    trials: 'MERIT-UC and supportive observational data',
    responseRate: 'Evidence in UC is limited compared with Crohn’s disease',
    remissionRate: 'Inconsistent UC remission signal',
    keySideEffects: 'Nausea, liver toxicity, cytopenias, teratogenicity',
    yearApproved: '1988',
    notes: 'Sometimes used in practice, but the brief correctly notes that UC data are much thinner than for Crohn’s disease.',
  },
  {
    id: 20,
    rank: 20,
    name: 'Mesalamine Suppositories / Enemas',
    className: 'Rectal therapy',
    route: 'Rectal',
    severity: 'Proctitis or left-sided UC',
    trials: 'Multiple distal UC rectal mesalamine trials',
    responseRate: 'Rapid local symptom response in distal disease',
    remissionRate: '~65-75% for distal UC',
    keySideEffects: 'Rectal discomfort, urgency, mild leakage, rare intolerance',
    yearApproved: '1989 (formulation-specific)',
    notes: 'One of the most effective local therapies in the entire brief when inflammation is limited to the rectum or left colon.',
  },
  {
    id: 21,
    rank: 21,
    name: 'Corticosteroid Enemas',
    className: 'Rectal therapy',
    route: 'Rectal',
    severity: 'Second-line local therapy',
    trials: 'Hydrocortisone and budesonide enema studies',
    responseRate: 'Useful when rectal mesalamine is insufficient or not tolerated',
    remissionRate: 'Lower local remission performance than rectal mesalamine',
    keySideEffects: 'Rectal irritation, local discomfort, steroid exposure',
    yearApproved: '1970s (formulation-specific)',
    notes: 'Often chosen after mesalamine-based rectal therapy, especially for left-sided symptoms.',
  },
  {
    id: 22,
    rank: 22,
    name: 'Proctocolectomy with IPAA (J-pouch)',
    className: 'Surgical',
    route: 'Operation',
    severity: 'Refractory disease, dysplasia, or cancer prevention',
    trials: 'Long-term IPAA cohort and surgical outcomes studies',
    responseRate: 'Curative for colonic disease',
    remissionRate: '~95% functional success',
    keySideEffects: 'Pouchitis, bowel frequency, obstruction risk, fertility impact after pelvic surgery',
    yearApproved: 'Standardized in the modern era rather than drug-approved',
    notes: 'Surgery is the definitive option when medical therapy fails or when dysplasia/cancer risk changes the equation.',
  },
]

export const TREATMENT_GROUPS = [
  '5-ASA / Aminosalicylate',
  'Biologic, anti-TNF',
  'Biologic, anti-integrin (gut selective)',
  'Biologic, anti-IL-12/23',
  'Biologic, anti-IL-23p19',
  'Small molecule, pan-JAK inhibitor',
  'Small molecule, selective JAK1 inhibitor',
  'Small molecule, S1P receptor modulator',
  'Corticosteroid',
  'Immunomodulator',
  'Rectal therapy',
  'Surgical',
] as const
